### ISSUE TITLE
签到报错没有权限

### ISSUE THREAD

**Issue by HIGHBu** [Adonis142857/GLaDOS-Signin#4]
{
    "code": -2,
    "message": "没有权限"
}
cookie按照图里的方式复制了，但是一直都没有权限，能帮忙解答一下吗
![image](https://github.com/Adonis142857/GLaDOS-Signin/assets/67864207/ab7b502c-bd00-4793-914f-389be8f9c03c)

**Comment by Adonis142857** [comment]
错误日志是什么

**Comment by ksws0134422** [comment]
错误日志是"code": -2,
"message": "没有权限"

**Comment by Adonis142857** [comment]
> 错误日志是"message": "oops, token error
官方修改了Token，已经更新，请拉取最新代码
